# Servidor
server.port=8080

# Conexión a Base de Datos (credenciales desde .env)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.cloud.config.enabled=false

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Esquema de base de datos
spring.flyway.schemas=gestor_pagos

# API GestoPago (valores desde .env)
gestopago.auth.url=${GESTOPAGO_AUTH_URL}
gestopago.auth.id-distribuidor=${GESTOPAGO_AUTH_ID_DISTRIBUIDOR}
gestopago.auth.codigo-dispositivo=${GESTOPAGO_AUTH_CODIGO_DISPOSITIVO}
gestopago.auth.password=${GESTOPAGO_AUTH_PASSWORD}